// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCServiceClient is the client API for RPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCServiceClient interface {
	GetDataByHash(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*ResData, error)
	SendContribution(ctx context.Context, in *ReqContribution, opts ...grpc.CallOption) (*ResStateHash, error)
	SendFinalContribution(ctx context.Context, in *ReqContribution, opts ...grpc.CallOption) (*ResEmpty, error)
}

type rPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCServiceClient(cc grpc.ClientConnInterface) RPCServiceClient {
	return &rPCServiceClient{cc}
}

func (c *rPCServiceClient) GetDataByHash(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*ResData, error) {
	out := new(ResData)
	err := c.cc.Invoke(ctx, "/RPCService/GetDataByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServiceClient) SendContribution(ctx context.Context, in *ReqContribution, opts ...grpc.CallOption) (*ResStateHash, error) {
	out := new(ResStateHash)
	err := c.cc.Invoke(ctx, "/RPCService/SendContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCServiceClient) SendFinalContribution(ctx context.Context, in *ReqContribution, opts ...grpc.CallOption) (*ResEmpty, error) {
	out := new(ResEmpty)
	err := c.cc.Invoke(ctx, "/RPCService/SendFinalContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServiceServer is the server API for RPCService service.
// All implementations must embed UnimplementedRPCServiceServer
// for forward compatibility
type RPCServiceServer interface {
	GetDataByHash(context.Context, *ReqHash) (*ResData, error)
	SendContribution(context.Context, *ReqContribution) (*ResStateHash, error)
	SendFinalContribution(context.Context, *ReqContribution) (*ResEmpty, error)
	mustEmbedUnimplementedRPCServiceServer()
}

// UnimplementedRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServiceServer struct {
}

func (UnimplementedRPCServiceServer) GetDataByHash(context.Context, *ReqHash) (*ResData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataByHash not implemented")
}
func (UnimplementedRPCServiceServer) SendContribution(context.Context, *ReqContribution) (*ResStateHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendContribution not implemented")
}
func (UnimplementedRPCServiceServer) SendFinalContribution(context.Context, *ReqContribution) (*ResEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFinalContribution not implemented")
}
func (UnimplementedRPCServiceServer) mustEmbedUnimplementedRPCServiceServer() {}

// UnsafeRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServiceServer will
// result in compilation errors.
type UnsafeRPCServiceServer interface {
	mustEmbedUnimplementedRPCServiceServer()
}

func RegisterRPCServiceServer(s grpc.ServiceRegistrar, srv RPCServiceServer) {
	s.RegisterService(&RPCService_ServiceDesc, srv)
}

func _RPCService_GetDataByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).GetDataByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCService/GetDataByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).GetDataByHash(ctx, req.(*ReqHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCService_SendContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).SendContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCService/SendContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).SendContribution(ctx, req.(*ReqContribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCService_SendFinalContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqContribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).SendFinalContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RPCService/SendFinalContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).SendFinalContribution(ctx, req.(*ReqContribution))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCService_ServiceDesc is the grpc.ServiceDesc for RPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RPCService",
	HandlerType: (*RPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataByHash",
			Handler:    _RPCService_GetDataByHash_Handler,
		},
		{
			MethodName: "SendContribution",
			Handler:    _RPCService_SendContribution_Handler,
		},
		{
			MethodName: "SendFinalContribution",
			Handler:    _RPCService_SendFinalContribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
